name: Pull request development

on:
  pull_request:

jobs:
  test:
    name: Lint & Test
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message , '[skip ci]')"
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: yarn
          registry-url: https://npm.pkg.github.com

      - name: Install Dependencies
        run: yarn install --frozen-lockfile --non-interactive
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GIT_PACKAGES_TOKEN }}

      - name: Run linters
        uses: wearerequired/lint-action@v1
        with:
          prettier: false
          eslint: true
          auto_fix: true
          commit_message: 'fix: code style issues with ${linter}'

      - name: Test
        run: |
          yarn test:ci
